# Generated by Django 6.0.6 on 2026-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_deleted_at_contact_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='relationship_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
