# Generated by Django 6.0.6 on 2026-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_relationship_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
