# Generated by Django 6.0.6 on 2026-07-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ai_follow_up_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
