# Generated by Django 6.0.6 on 2026-07-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_ai_follow_up_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ai_follow_up_suggestions',
        ),
        migrations.AddField(
            model_name='contact',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='summary_status',
            field=models.CharField(choices=[('NOT_GENERATED', 'Not Generated'), ('READY', 'Ready'), ('STALE', 'Stale'), ('GENERATING', 'Generating')], default='NOT_GENERATED', max_length=20),
        ),
    ]
