# Generated by Django 6.0.6 on 2026-07-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleaccount',
            options={'verbose_name': 'Google Account', 'verbose_name_plural': 'Google Accounts'},
        ),
    ]
