# Generated by Django 6.0.6 on 2026-06-20 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CALL', 'Call'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('LINKEDIN', 'LinkedIn Message')], max_length=20)),
                ('notes', models.TextField()),
                ('interaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact')),
            ],
        ),
    ]
