# Generated by Django 6.0.6 on 2026-07-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_google_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_access_token',
        ),
    ]
