from rest_framework.routers import DefaultRouter

from .views import ContactViewSet

router = DefaultRouter()   #generate the urls for the viewset automatically
router.register(r"contacts", ContactViewSet)

urlpatterns = router.urls   #Use all URLs generated by router