from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import ContactViewSet, ExportContactsView, ImportContactsView

router = DefaultRouter()   #generate the urls for the viewset automatically
router.register(r"contacts", ContactViewSet)

urlpatterns = [
    path(
        "contacts/export/",
        ExportContactsView.as_view(),
    ),
    path(
        "contacts/import/",
        ImportContactsView.as_view(),
    )
]
urlpatterns += router.urls   #Use all URLs generated by router

